version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run:
          name: Create .circleci directory
          command: mkdir -p .circleci

      # Additional steps for your build process go here

workflows:
  version: 2
  build:
    jobs:
      - build

