version: 2.1

jobs:
  ssh-and-create-directory:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "d1:6a:a7:20:49:5e:6e:5e:fc:7b:35:38:b8:ae:7f:af"

      - run:
          name: SSH into EC2 Instance and Create Directory
          command: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@your_instance_ip "mkdir -p /home/ubuntu/saud4567/.circleci"

