version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Add your SSH keys
      - add_ssh_keys:
          fingerprints:
            - "35:ea:0f:df:b5:f1:97:33:dc:c1:81:a7:85:6b:a7:2e"

      # Example: SSH into a remote server and run a deployment script
      - run:
          name: Deploy to Remote Server
          command: |
            ssh -o StrictHostKeyChecking=no -v ubuntu@34.244.215.8 "/home/ubuntu/saud4567/.circleci/config.yml"

workflows:
  version: 2
  deploy-to-remote:
    jobs:
      - deploy
